### ISSUE TITLE
How to use Node neighborhood matrix instead of meta paths in HanConv?

### ISSUE THREAD

**Issue by faizan1234567** [pyg-team/pytorch_geometric#7757] opened 2023-07-17 14:25 UTC
### 🐛 Describe the bug

Dear Author, 

Thanks for the great work. We are working on hypergraph implementation on TU Datasets. As part of our algorithm, we need to use HanConv. According to the documentation of [HanConv](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.HANConv.html#torch_geometric.nn.conv.HANConv) class, it supports meta paths. However, we are not using meta paths instead we are employing a node neighborhood matrix. Which describes node connections in the graph based on the shortest distance we calculated between nodes. If the node distance between nodes is less than that threshold we consider it a neighbor of that node. And the NxN connection matrix describes nodes' connection in the graph where N is the number of nodes in the graph.  And matrix has entries with 0s and 1s.  If two nodes are connected based on the above method the entry between two nodei and nodej is set to 1.  How can we use HanConv with this relationship and matrix? Basically, I think we need to encode each row as a meta path.

for example, if there are 5 nodes as follows:

------------------------------------------------

` matrix`
`-->`
      a1     a2    a3         a4        a5
a1   0        1        1        0         1
a2   1        0        0        0         1
a3   1        0        0        1         0
a4   0        0        1        0         1
a5   1        1        0        1         0

In the above matrix, in the first row, "a1" is connected with [a2, a3, a5], similarly, a2 is connected with [a1, a5], and so on.
so the first row has a meta path-like connection, and likewise other rows. Therefore, my question is how can we use HanConv with this setting? I hope I am clear. If not please let me know.

**Comment by rusty1s** [comment] 2023-07-31 12:07
Duplicate of https://github.com/pyg-team/pytorch_geometric/issues/7815

**Closed by rusty1s** 2023-07-31 12:07 UTC
Labels: bug
