### ISSUE TITLE
NeighborLoader on SparseTensor gives shape mismatch

### ISSUE THREAD

**Issue by nabihach** [pyg-team/pytorch_geometric#4346] opened 2022-03-26 00:27 UTC
### 🐛 Describe the bug

I am trying to use the NeighborLoader on the OGB_MAG dataset (converted to SparseTensor), but I get the following runtime error about a shape mismatch:

```
import torch
import os
from torch_geometric.datasets import OGB_MAG
from torch_geometric.data import Data
from torch_geometric.loader import NeighborLoader
from torch_geometric.nn import GCNConv
import torch_geometric.transforms as T

path = os.path.join('..', 'data', 'OGB_MAG')
mag_dataset = OGB_MAG(path)
mag_data = mag_dataset[0]

hidden_channels=256
model = GCNConv(hidden_channels, hidden_channels, cached=True)

data = Data(x=mag_data['paper'].x, y=mag_data['paper'].y, edge_index=mag_data[('paper','cites','paper')].edge_index)
data = T.ToSparseTensor(remove_edge_index=False)(data)
print(data)
>>> Data(x=[736389, 128], edge_index=[2, 5416271], y=[736389], adj_t=[736389, 736389, nnz=5416271])

loader = NeighborLoader(data, num_neighbors=[10] * 2, shuffle=True, directed=False, input_nodes=mag_data['paper'].train_mask, batch_size=16)
batch = next(iter(loader))
print(batch)
>>> Data(x=[518, 128], edge_index=[2, 1202], y=[518], adj_t=[518, 518, nnz=1202], batch_size=16)

model(batch.x, batch.adj_t)
>>>RuntimeError: shape mismatch: value tensor of shape [1202] cannot be broadcast to indexing result of shape [1146]

```

I'm confused as to why this is happening?

Full stack trace:

```
--------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [7], in <cell line: 3>()
      1 batch = next(iter(loader))
      2 print(batch)
----> 3 model(batch.x, batch.adj_t)

File /anaconda/envs/venvconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:1102, in Module._call_impl(self, *input, **kwargs)
   1098 # If we don't have any hooks, we want to skip the rest of the logic in
   1099 # this function, and just call forward.
   1100 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1101         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1102     return forward_call(*input, **kwargs)
   1103 # Do not call functions when jit is used
   1104 full_backward_hooks, non_full_backward_hooks = [], []

File /anaconda/envs/venvconda3/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py:183, in GCNConv.forward(self, x, edge_index, edge_weight)
    181 cache = self._cached_adj_t
    182 if cache is None:
--> 183     edge_index = gcn_norm(  # yapf: disable
    184         edge_index, edge_weight, x.size(self.node_dim),
    185         self.improved, self.add_self_loops)
    186     if self.cached:
    187         self._cached_adj_t = edge_index

File /anaconda/envs/venvconda3/lib/python3.8/site-packages/torch_geometric/nn/conv/gcn_conv.py:42, in gcn_norm(edge_index, edge_weight, num_nodes, improved, add_self_loops, dtype)
     40     adj_t = adj_t.fill_value(1., dtype=dtype)
     41 if add_self_loops:
---> 42     adj_t = fill_diag(adj_t, fill_value)
     43 deg = sparsesum(adj_t, dim=1)
     44 deg_inv_sqrt = deg.pow_(-0.5)

File /anaconda/envs/venvconda3/lib/python3.8/site-packages/torch_sparse/diag.py:91, in fill_diag(src, fill_value, k)
     89 if value is not None:
     90     sizes = [num_diag] + src.sizes()[2:]
---> 91     return set_diag(src, value.new_full(sizes, fill_value), k)
     92 else:
     93     return set_diag(src, None, k)

File /anaconda/envs/venvconda3/lib/python3.8/site-packages/torch_sparse/diag.py:48, in set_diag(src, values, k)
     45 diag = torch.arange(start, start + num_diag, device=row.device)
     47 new_row = row.new_empty(mask.size(0))
---> 48 new_row[mask] = row
     49 new_row[inv_mask] = diag
     51 new_col = col.new_empty(mask.size(0))

RuntimeError: shape mismatch: value tensor of shape [1202] cannot be broadcast to indexing result of shape [1146]
```

**Comment by rusty1s** [comment] 2022-03-26 12:24
Thanks for reporting. This is indeed a bug. It is caused by the fact that our sampling procedure does not return sorted neighbors for each node. This leads to a bug during addition of self-loops (which leverages the fact of sorted neighbor indices). For now, this bug is easily fixable via re-sorting the indices. I pushed a fix in https://github.com/pyg-team/pytorch_geometric/commit/300f005bdb8fc81adfe3985106bc65f34059bbe1.

A better solution is to fix this directly inside the `neighbor_sample` procedure.

Also not that you do not want to set `cache=True` inside `GCNConv` in case you are operating on mini-batches of graphs.

**Closed by rusty1s** 2022-03-26 12:24 UTC
Labels: bug
