### ISSUE TITLE
Problem with  torch_geometric.transforms

### ISSUE THREAD

**Issue by giladsegal10** [pyg-team/pytorch_geometric#8341] opened 2023-11-07 18:06 UTC
### 🐛 Describe the bug

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-20-2b41d296395c>](https://localhost:8080/#) in <cell line: 7>()
      5 import torch.nn as nn
      6 import torch.nn.functional as F
----> 7 import torch_geometric.transforms as T
      8 from tqdm.auto import tqdm
      9 

3 frames
[/usr/local/lib/python3.10/dist-packages/torch_geometric/__init__.py](https://localhost:8080/#) in <module>
----> 1 import torch_geometric.utils
      2 import torch_geometric.data
      3 import torch_geometric.sampler
      4 import torch_geometric.loader
      5 import torch_geometric.transforms

[/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/__init__.py](https://localhost:8080/#) in <module>
      1 import copy
      2 
----> 3 from .scatter import scatter, group_argsort
      4 from .segment import segment
      5 from .sort import index_sort

[/usr/local/lib/python3.10/dist-packages/torch_geometric/utils/scatter.py](https://localhost:8080/#) in <module>
      5 
      6 import torch_geometric.typing
----> 7 from torch_geometric import warnings
      8 from torch_geometric.typing import torch_scatter
      9 from torch_geometric.utils.functions import cumsum

[/usr/local/lib/python3.10/dist-packages/torch_geometric/warnings.py](https://localhost:8080/#) in <module>
      3 import torch_geometric
      4 
----> 5 if torch_geometric.typing.WITH_PT20:  # pragma: no cover
      6     from torch._dynamo import is_compiling as _is_compiling
      7 else:

AttributeError: partially initialized module 'torch_geometric' has no attribute 'typing' (most likely due to a circular import)

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.1.0+cu118
* OS: Windows
* Python version: 3.10.12
* CUDA/cuDNN version:
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
cuDNN version: 8900
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment] 2023-11-08 15:38
Will be hopefully fixed by https://github.com/pyg-team/pytorch_geometric/pull/8343. I cannot reproduce it myself :(

**Closed** 2023-11-08 16:02 UTC
Labels: bug
