### ISSUE TITLE
RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation

### ISSUE THREAD

**Issue by monk1337** [pyg-team/pytorch_geometric#3175] opened 2021-09-18 13:00 UTC
I am trying to use GCN and GAT from library and getting this error :

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/torch_scatter/scatter.py", line 21, in softmax
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return out.scatter_add_(dim, index, src)
RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```

I tried to add `torch.use_deterministic_algorithms(True)` but not working
Same code is working well on CPU.
How I can avoid this error?

**Comment by rusty1s** [comment] 2021-09-19 13:09
`scatter_*` is not a deterministic operation, and using `torch.use_deterministic_algorithms(True)` will result in an error. If you want to make use of deterministic operations in PyG, you have to use the `SparseTensor` class as an alternative to `edge_index`, see [here](https://pytorch-geometric.readthedocs.io/en/latest/notes/sparse_tensor.html).

**Comment by monk1337** [comment] 2021-09-20 05:14
@rusty1s Could you shed a little more light on this? The result will be the same as I can see from [example ](https://pytorch-geometric.readthedocs.io/en/latest/notes/sparse_tensor.html) then what the difference and issue is? And is there any accuracy difference between them?

**Comment by rusty1s** [comment] 2021-09-20 06:13
Sure. The difference between those two approaches is that, for `scatter`, the order of aggregation is not deterministic since internally `scatter` is implemented by making use of atomic operations. This may lead to slightly different outputs induced by floating point precision, e.g., `3 + 2 + 1 = 5.000001` while `1 + 2 + 3 = 4.9999999`. In contrast, the order of aggregation in `SparseTensor` is always deterministic and is performed based on the ordering of node indices. In practice, either operation works fine, in particular because graphs do not usually obey a fixed size ordering. The final accuracy is usually the same.

**Comment by monk1337** [comment] 2021-09-20 11:24
Thank you very much for explanation :)

**Comment by monk1337** [comment] 2021-09-21 11:35
Sorry for reopening the issue again; I tried the above solution with the GCNConv method, and it works fine, but using the SparseTensor method with GATConv throwing this error 


`RuntimeError: index_add_cuda_ does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.`

**Comment by rusty1s** [comment] 2021-09-21 13:02
Can you show me a script to reproduce? I have no problems running the following script:
```python
import torch
from torch_geometric.nn import GATConv
from torch_geometric.datasets import Planetoid
import torch_geometric.transforms as T

torch.use_deterministic_algorithms(True)

data = Planetoid('/tmp/dawdh', name='Cora', transform=T.ToSparseTensor())[0]
data = data.cuda()

conv = GATConv(data.num_node_features, 20, heads=4)
conv = conv.cuda()

out = conv(data.x, data.adj_t)
out.mean().backward()
```

**Comment by rusty1s** [comment] 2022-02-23 08:25
Thanks for the reference @aabbas90. In my understanding, deterministic `scatter` is automatically supported for 1D tensors in case you set `torch.use_deterministic_algorithms(True)`, right?

Notably, I'm afraid that operating on 1D tensors will actually never be the case in PyG (as this requires that the number of features needs to be one).

**Comment by aabbas90** [comment] 2022-02-23 08:43
Yes deterministic `scatter` is automatically supported for 1D tensors. You are right though as most of the times multi-dimensional features would need to be used. The only exception I found is when we are calculating attention weights for transformer related architectures as they are 1D e.g. here:

https://github.com/pyg-team/pytorch_geometric/blob/15cf910116b3eb31310a74d75fa9b2c1789e977b/torch_geometric/utils/softmax.py#L44

But I guess it does not help much since other ops would still be non-deterministic.

**Comment by rusty1s** [comment] 2022-02-23 08:57
Ah, I see. In that case we would need to try to `squeeze` the tensor into a one-dimensional, got it. In that case, it might be better to add this functionality directly inside `torch-scatter`. Are you interested in contributing this?

**Comment by rusty1s** [comment] 2022-02-25 10:03
Please let me know the issues when installing `torch-scatter` from source. You can probably also try to simply compile the CPU version via `FORCE_ONLY_CPU=1 python setup.py develop`.

**Comment by aabbas90** [comment] 2022-02-25 10:43
The error I am getting is:

```
$ python
>>> import torch_scatter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/projects/pytorch_scatter/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/anaconda3/envs/py_scatter/lib/python3.7/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/anaconda3/envs/py_scatter/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /projects/pytorch_scatter/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv
```
To install from source I did the following inside a conda environment with python 3.7:
```
conda install pytorch cudatoolkit=10.2 -c pytorch
CPATH=/usr/lib/cuda-10.2/include/ python setup.py develop
```

where `PATH=/anaconda3/envs/py_scatter/bin:/anaconda3/condabin:/software/gcc-7.5-build/bin:/usr/lib/cuda-10.2/bin:...`

**Comment by rusty1s** [comment] 2022-02-25 11:20
Can you uninstall and try to install CPU-only (as detailed above). Please report any installation logs as well.

**Comment by andrei-rusu** [comment] 2022-03-03 20:16
Sorry for intervening in your discussion, but I have a question regarding the workaround posted here for the OP issue:
Is there any way one could bypass the non-deterministic issue of scatter by utilizing SparseTensors, while also retaining the ability to utilize edge attributes and self loops? It seems that this behaviour is currently missing, and unfortunately my GAT-based models seem to get a performance hit when I'm using SparseTensors and setting add_self_loops=False.
Thank you!

**Comment by rusty1s** [comment] 2022-03-04 21:16
The usage of `SparseTensor` ensures deterministic behavior while its output and training performance should be identical to `edge_index`. There shouldn't be any significant performance hit. If there exists one, it is probably induced by `add_self_loops=False`. Aany reason to disable it at all?

**Comment by andrei-rusu** [comment] 2022-03-05 03:22
If add_self_loop is enabled, a NotImplementedError arises (e.g. check the GATConv forward implementation).

**Comment by rusty1s** [comment] 2022-03-05 07:32
Can you clarify what you mean by one cannot omit setting `edge_dim`? I'm happy to fix it once I am sure about the issue.

Furthermore, note that you can always set `add_self_loops` in `GATConv` and apply self-loops to the `SparseTensor` in a pre-processing step (prior to any message passing), e.g., via transforms:
```python
transform = T.Compose([T.AddSelfLoops(), T.ToSparseTensor()])
```
This should mimic the original behavior.

**Comment by andrei-rusu** [comment] 2022-03-05 09:34
OK. So, in ``gat_conv.py`` in the ``forward()`` method you have the following logic which returns an error for SparseTensors if ``add_self_loops`` is True and ``edge_dim`` is set:
https://github.com/pyg-team/pytorch_geometric/blob/aa99b50c61743f3e33ef8a39ab6223c12f29786b/torch_geometric/nn/conv/gat_conv.py#L219-L239

At the same time, in ``message()`` you have the following assertion, which fails if one does not set ``edge_dim`` but passes in edge attributes (``self.lin_edge`` gets initialized only if ``edge_dim`` is not None):
https://github.com/pyg-team/pytorch_geometric/blob/aa99b50c61743f3e33ef8a39ab6223c12f29786b/torch_geometric/nn/conv/gat_conv.py#L272-L275

Maybe the intention here was to only support passing edge attributes directly to the SparseTensor constructor (i.e. without support for effectively setting ``edge_attr``? Nonetheless, I've been having some errors with doing it that way too (I'm away from my office computer, so I will get back on Monday with more details on those). At the same time, since I've written some Adapters to allow for the edge attributes to also be utilized as ``edge_weight`` or ``edge_type`` where the layer supports that, and I've also implemented the Linear projections of the ``edge_attr`` myself, utilizing the edge attributes from the SparseTensor requires some annoying code refactory on my part to support both modes as I only really need SparseTensors when running on CUDA with a set seed to ensure consistency.

**Comment by rusty1s** [comment] 2022-03-05 09:52
> you have the assertion below, which fails if one does not set edge_dim but passes in edge attributes (self.lin_edge gets initialized only if edge_dim is not None).

I think this is definitely intended. If you pass in `edge_attr` it shouldn't be ignored just because one didn't set `edge_dim`. The `GINEConv` layer does not have this constraint since it requires same input dimensionality across node and edge features (which comes with other disadvantages).

I guess the easiest workaround for your other problem would be the addition of self-loops in `SparseTensor` for multi-dimensional edge features as well, right? We would need to add support for this in `add_self_loops`.

**Comment by andrei-rusu** [comment] 2022-03-05 10:22
Well, from my understanding ``GINEConv`` requires the ``edge_attr`` to have a dimensionality of ``in_channels``. ``GATConv``, on the other hand, requires ``edge_attr`` to have a dimensionality of ``heads * out_channels``. I don't see why one wouldn't be able to create their own projections in order to ensure ``edge_attr`` has the correct size for each of these cases. I agree, however, that not enforcing ``edge_dim`` may be confusing to some (and the documentation is already explicit about this internal Linear layer), and I don't really have a problem with it as long as ``add_self_loops`` doesn't fail.

And yep, the final solution should be what you said in the second paragraph! However, as per your previous comment, a temporary workaround could be to just add the self loops as part of the Transform or directly to the original ``edge_index`` & ``edge_attr`` tensors before creating the SparseTensor. Thanks!

**Comment by cxw-droid** [comment] 2022-07-16 17:59
Hi, @rusty1s I try to make [mutag_gin.py](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/mutag_gin.py) output a deterministic result. Following the above suggestions, I have changed the dataset to SparseTensor, `edge_index` to `adj_t` and changed line 53 to `x = global_max_pool(x, batch)`, but I still got random result. I set the seed as follows:
```  
seed = 2
torch.manual_seed(seed)  ##
# np.random.seed(seed)
# random.seed(seed)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True
torch.use_deterministic_algorithms(True)
```
Any help would be appreciated. Thanks.

**Comment by FeiGSSS** [comment] 2022-11-07 22:36
> Hi, @rusty1s I try to make [mutag_gin.py](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/mutag_gin.py) output a deterministic result. Following the above suggestions, I have changed the dataset to SparseTensor, `edge_index` to `adj_t` and changed line 53 to `x = global_max_pool(x, batch)`, but I still got random result. I set the seed as follows:
> 
> ```
> seed = 2
> torch.manual_seed(seed)  ##
> # np.random.seed(seed)
> # random.seed(seed)
> torch.backends.cudnn.benchmark = False
> torch.backends.cudnn.deterministic = True
> torch.use_deterministic_algorithms(True)
> ```
> 
> Any help would be appreciated. Thanks.

I have encontered the same problem, have you figured it out?

**Comment by rusty1s** [comment] 2022-11-10 15:01
You need to use `torch_scatter.segment_csr(x, batch.ptr)` instead of `global_max_pool`.

**Comment by akihironitta** [comment] 2024-01-11 13:17
Closing this issue as there seems no action item, but feel free to create a new issue or discussion.

**Closed by akihironitta** 2024-01-11 13:17 UTC
Labels: feature, help wanted, 0 - Priority P0, determinism

**Comment by vito-GitHub** [comment] 2025-04-01 02:56
Hello, how to solve the determinism of floating-point type in cuda?
