### ISSUE TITLE
Impossible to use TUDataset

### ISSUE THREAD

**Issue by svnv-svsv-jm** [pyg-team/pytorch_geometric#9521] opened 2024-07-19 08:26 UTC
### 🐛 Describe the bug

Just trying to create a `TUDataset` dataset raises an error.

If I do:

```python
dataset = TUDataset(root=data_path, name="PROTEINS")
```

I get:

```
data_path = './.data'

    def test_sampling_from_pyg_loader(data_path: str) -> None:
        """Test."""
>       dataset = TUDataset(root=data_path, name="PROTEINS")

tests/utils/test_data_utils.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../../../.pyenv/versions/3.10.13/envs/brainiac-2-privacy/lib/python3.10/site-packages/torch_geometric/datasets/tu_dataset.py:129: in __init__
    super().__init__(root, transform, pre_transform, pre_filter,
../../../../../.pyenv/versions/3.10.13/envs/brainiac-2-privacy/lib/python3.10/site-packages/torch_geometric/data/in_memory_dataset.py:81: in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log,
../../../../../.pyenv/versions/3.10.13/envs/brainiac-2-privacy/lib/python3.10/site-packages/torch_geometric/data/dataset.py:112: in __init__
    self._download()
../../../../../.pyenv/versions/3.10.13/envs/brainiac-2-privacy/lib/python3.10/site-packages/torch_geometric/data/dataset.py:229: in _download
    self.download()
../../../../../.pyenv/versions/3.10.13/envs/brainiac-2-privacy/lib/python3.10/site-packages/torch_geometric/datasets/tu_dataset.py:199: in download
    fs.mv(filename, osp.join(self.raw_dir, osp.basename(filename)))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path1 = '/Users/gianmarcoaversano/Documents/jobs/enx/drive/brainiac-2-privacy/.data/PROTEINS/raw/PROTEINS/PROTEINS_node_labels.txt'
path2 = '.data/PROTEINS/raw/PROTEINS_node_labels.txt', recursive = True

    def mv(path1: str, path2: str, recursive: bool = True) -> None:
        fs1 = get_fs(path1)
        fs2 = get_fs(path2)
        assert fs1.protocol == fs2.protocol
>       fs1.mv(path1, path2, recursive)
E       TypeError: LocalFileSystem.mv() takes 3 positional arguments but 4 were given

../../../../../.pyenv/versions/3.10.13/envs/brainiac-2-privacy/lib/python3.10/site-packages/torch_geometric/io/fs.py:193: TypeError
```

### Versions

```
pytorch-lightning                 2.3.3
torch                             2.3.1
torch_cluster                     1.6.3
torch_geometric                   2.5.3
torch-scatter                     2.1.2
torch-sparse                      0.6.18
torch-spline-conv                 1.2.2
torchmetrics                      1.4.0.post0
torchquad                         0.3.0
torchvision                       0.18.1
```

**Comment by kano5266** [comment] 2024-07-19 13:10
I think this is fixed in https://github.com/pyg-team/pytorch_geometric/pull/9436

**Comment by akihironitta** [comment] 2024-07-19 18:14
Duplicate of #9329. Feel free to let us know if the issue still persists on master.

**Closed by akihironitta** 2024-07-19 18:14 UTC
Labels: bug
