### ISSUE TITLE
NeighborLoader PyG 2.0.1

### ISSUE THREAD

**Issue by dahe-cvl** [pyg-team/pytorch_geometric#3198] opened 2021-09-22 11:16 UTC
## 🐛 Bug

Hi,

I am facing some issues with the new NeighborLoader (from torch_geometric.loader import NeighborLoader).

I try to implement and train a node classification network.  I use the Cora dataset for setting up the environment and the first experiments. I can observe that the RAM memory increases with every epoch while loading the batches. 
For larger graphs, different settings for num_neighbors the code runs into a RAM-overload issue.

Do you know about the problem? Is there any workaround for it?

## To Reproduce

Here is a small code snippet to reproduce the behavior.

```
dataset = Planetoid("./data/Cora", 'Cora', transform=T.NormalizeFeatures())
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
train_loader = NeighborLoader(data,
                                  num_neighbors=[10]*2,
                                  batch_size=128,
                                  input_nodes=data.train_mask,
                                  shuffle=True,
                                  num_workers=4,
                                  replace=True,
                                  directed=True
                                )
num_epochs = 10000
for i in range(0, num_epochs):
       for data_batch in train_loader:
             print(data_batch)
```
    

## Expected behavior

I would expect that the memory does not increase with training time. It seems that the "old" batches are stored somewhere in the background. 

Can you reproduce the problem?

## Environment

* OS: Ubuntu 20.04.3 LTS 
* Python version: Python 3.8.10 
* PyTorch version ( pytorch geometric):
torch                 1.8.0+cu101
torch-cluster         1.5.9
torch-geometric       2.0.1
torch-scatter         2.0.8
torch-sparse          0.6.12
torch-spline-conv     1.2.1
torchaudio            0.8.0
torchvision           0.9.0+cu101

Many thanks in advance!
Best regards
Daniel

**Comment by rusty1s** [comment] 2021-09-22 11:43
Thanks for reporting, in particular, because I cannot reproduce this issue. Both `top` and the Python garbage collector do not show an increase in CPU memory for me:
```python
from torch_geometric.datasets import Planetoid
from torch_geometric.loader import NeighborLoader
from torch_geometric.profile import get_cpu_memory_from_gc

dataset = Planetoid("./data/Cora", 'Cora')
data = dataset[0]
train_loader = NeighborLoader(data, num_neighbors=[100] * 2, batch_size=128,
                              input_nodes=data.train_mask, shuffle=True,
                              num_workers=4, replace=True, directed=True)
num_epochs = 10000
for i in range(0, num_epochs):
    for data_batch in train_loader:
        pass
     print(f'{get_cpu_memory_from_gc() / (1024 * 1024):.4f}')
```
Does the output of `get_cpu_memory_from_gc` keeps constant for you?

**Comment by dahe-cvl** [comment] 2021-09-22 12:03
thanks for the quick reply.

I test the code now with the same settings in the NeihgborLoader as you did. 
The output of "get_cpu_memory_from_gc" keeps constant. in average 17.0 
However, top and htop show me an increase in memory usage over time. ( it goes up to 50GB)

Can you tell me which torch versions (torch, torch-geometric, ...) you exactly use in your python environment?

many thanks!

**Comment by rusty1s** [comment] 2021-09-22 12:30
I'm using the latest versions of extension packages (`torch-scatter`, `torch-sparse`) and PyG from master. As the garbage collector does not report an increase in memory, this is likely induced in the C++ sampling part.

**Comment by dahe-cvl** [comment] 2021-09-22 12:33
Meanwhile, I run the code snippet also on a different machine and I also created the python environment completely new (with torch 1.8.x and torch 1.9.x , also with the latest extension packs...) but I can observe the same issue with the memory.

**Comment by rusty1s** [comment] 2021-09-23 10:03
I see. I can now see the increase in memory consumption as well (`num_workers=0` seems to be working just fine though).

**Comment by dahe-cvl** [comment] 2021-09-23 10:06
thank you for the reply.... ok num_workers=0 is a valid selection?
I will try it and give you feedback.

**Comment by dahe-cvl** [comment] 2021-09-23 10:11
ok, same observation on my machine with my settings. if I set the num_workers parameter to 0 the memory does not increase anymore.

**Comment by rusty1s** [comment] 2021-09-23 12:09
Furthermore, using `persistent_workers=True` in case `num_workers > 0` eliminates this problem as well. I'm still digging into the cause of this issue.

**Comment by rusty1s** [comment] 2021-09-23 12:16
This seems to be related to https://github.com/PyTorchLightning/pytorch-lightning/issues/2352. I fixed it for now by setting `persistent_workers=True` in case `num_workers>0`, see https://github.com/pyg-team/pytorch_geometric/commit/635154b1de79332bcbd16c7ec135ae26ab98e91c.

**Comment by rusty1s** [comment] 2021-09-23 12:19
And https://github.com/pytorch/pytorch/issues/13246

**Comment by dahe-cvl** [comment] 2021-09-23 12:25
ah ok! the fix is working now. thanks a lot for your support!

**Comment by rusty1s** [comment] 2021-09-23 12:35
I'm closing this since there is not much we can do on our side. Feel free to re-open it anytime.

**Closed by rusty1s** 2021-09-23 12:35 UTC
Labels: bug, Priority P0
