### ISSUE TITLE
training not converging in han_imdb.py

### ISSUE THREAD

**Issue by gamersover** [pyg-team/pytorch_geometric#4527] opened 2022-04-25 08:51 UTC
I had ran examples/hetero/han_imdb.py, and the result looks not good.
![企业微信截图_1650875854377](https://user-images.githubusercontent.com/26238198/165052332-9a64144c-6127-4c5c-a73d-db6fe2bc1ecb.png)

**Comment by rusty1s** [comment] 2022-04-25 09:59
Duplicate of https://github.com/pyg-team/pytorch_geometric/discussions/4526.

**Closed by rusty1s** 2022-04-25 09:59 UTC
