### ISSUE TITLE
Data Batch problem in PyG

### ISSUE THREAD

**Issue by Amadeus-System** [pyg-team/pytorch_geometric#4848] opened 2022-06-23 05:40 UTC
### 🐛 Describe the bug

Hi. I am a computational physics researcher and was using PyG very well.
my pyg code was working well a few weeks ago, but now that I run my code, it is not working anymore without any changes.

the problem is like below.
I have many material structures and in my "custom_dataset" class, these are preprocessed and all graph informations (node features, edge features, edge index etc) are inserted into "Data" object in PyTorch geometric.
You can see that each preprocessed sample with index $i$ was printed normal "Data" object in pyg

![캡처2](https://user-images.githubusercontent.com/76824867/175221069-874bf9b1-308b-4d99-8459-b3479307e78a.PNG)

But When I insert my custom dataset class into pyg DataLoader and I did like below,

``` Python
sample = next(iter(train_loader)) # batch sample
```

batch sample is denoted by "DataDataBatch". I didn't see this kind of object name.
and i can't use "sample.x' or "sample.edge_index" command. Instead I need to do like this

![캡처3](https://user-images.githubusercontent.com/76824867/175222628-75eee3a2-869a-4c80-8dd5-5f0f160682f0.PNG)

I want to use expressions like "sample.x", "sample.edge_index" or "sample.edge_attr" as like before. 
I expect your kind explanations. Thank you.

### Environment

* PyG version: `2.0.5`
* PyTorch version: `1.11.0+cu113`
* OS: `GoogleColab Pro Plus`
* Python version: `Python 3.7.13 in colab`
* CUDA/cuDNN version:
* How you installed PyTorch and PyG (`conda`, `pip`, source): 
``` python
# Install required packages.
import os
import torch
os.environ['TORCH'] = torch.__version__
print(torch.__version__)
!pip install -q torch-scatter -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q torch-sparse -f https://data.pyg.org/whl/torch-${TORCH}.html
!pip install -q git+https://github.com/pyg-team/pytorch_geometric.git
!pip install -q pymatgen==2020.11.11  
```
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment] 2022-06-23 11:21
`DataDataBatch` indeed suggests that there is something weird going on. I am not able to reproduce this on any of our examples though. Do you have a minimal script to reproduce? This would help us out a lot!

**Comment by rusty1s** [comment] 2022-06-23 11:21
cc @mananshah99 Related to recent changes to dynamic inheritance?

**Comment by mananshah99** [comment] 2022-06-23 18:40
Acknowledged, will take a look shortly.

**Comment by Amadeus-System** [comment] 2022-06-25 23:25
Here is an image captured in a few weeks ago

The object name is "DataBatch" clearly.

![캡처](https://user-images.githubusercontent.com/76824867/175793387-93f87337-58ba-46cf-8a5d-4cd027d17687.PNG)

**Comment by Amadeus-System** [comment] 2022-06-25 23:43
I have solve this problem! I just downgraded current version(2.0.5) of PyG to previous version (2.0.4). 

However.. I hope you guys should fix this problem soon.

**Comment by rusty1s** [comment] 2022-06-25 23:52
The name `DataBatch` is correct. Is this for 2.0.4 or 2.0.5? Can you share an example that reproduces the issue?

**Comment by Amadeus-System** [comment] 2022-06-29 04:17
> The name `DataBatch` is correct. Is this for 2.0.4 or 2.0.5? Can you share an example that reproduces the issue?

my problem occured in pyg version 2.0.5.

**Comment by qcts33** [comment] 2022-07-07 08:13
I'm having the same problem.
## Example
``` python
from pprint import pprint

import networkx as nx
import torch as th
from torch_geometric.data import InMemoryDataset, LightningDataset
from torch_geometric.transforms import LocalDegreeProfile
from torch_geometric.utils import from_networkx


class PathGraph(InMemoryDataset):
    def __init__(
        self,
        root="data",
        transform=None,
        pre_transform=None,
        pre_filter=None,
    ):
        super().__init__(root, transform, pre_transform, pre_filter)
        self.data, self.slices = th.load(self.processed_paths[0])

    @property
    def raw_file_names(self):
        return [f"path_graph_{i}.gml" for i in range(3, 6)]

    @property
    def processed_file_names(self):
        return ["data.pt"]

    def download(self):
        graphs = (nx.path_graph(i) for i in range(3, 6))
        for g, p in zip(graphs, self.raw_paths):
            nx.write_gml(g, p)

    def process(self):
        graphs = map(nx.read_gml, self.raw_paths)
        graphs = list(graphs)
        data_list = [from_networkx(g) for g in graphs]

        if self.pre_filter is not None:
            data_list = [data for data in data_list if self.pre_filter(data)]

        if self.pre_transform is not None:
            data_list = [self.pre_transform(data) for data in data_list]

        data, slices = self.collate(data_list)
        th.save((data, slices), self.processed_paths[0])


def main():
    data_module = LightningDataset(
        train_dataset=PathGraph(transform=LocalDegreeProfile()),
        batch_size=2,
    )
    batch = next(iter(data_module.train_dataloader()))
    print("batch:")
    pprint(batch)
    print("batch.x:")
    pprint(batch.x)


if __name__ == "__main__":
    main()


```
The output is:
```
batch:
DataDataBatch(
  x={
    edge_index=[2, 10],
    num_nodes=7,
    x=[7, 5],
    batch=[7],
    ptr=[3]
  }
)
batch.x:
{'batch': tensor([0, 0, 0, 0, 1, 1, 1]),
 'edge_index': tensor([[0, 1, 1, 2, 2, 3, 4, 5, 5, 6],
        [1, 0, 2, 1, 3, 2, 5, 4, 6, 5]]),
 'num_nodes': 7,
 'ptr': tensor([0, 4, 7]),
 'x': tensor([[1.0000, 2.0000, 2.0000, 2.0000, 0.0000],
        [2.0000, 1.0000, 2.0000, 1.5000, 0.7071],
        [2.0000, 1.0000, 2.0000, 1.5000, 0.7071],
        [1.0000, 2.0000, 2.0000, 2.0000, 0.0000],
        [1.0000, 2.0000, 2.0000, 2.0000, 0.0000],
        [2.0000, 1.0000, 1.0000, 1.0000, 0.0000],
        [1.0000, 2.0000, 2.0000, 2.0000, 0.0000]])}
```
## Environment

-  PyG version: pyg-nightly=2.0.5.dev20220706
- PyTorch version: 1.12.0
- OS: ArchLinux
- Python version: 3.10.5 (conda_forge)
- CUDA/cuDNN version: 11.6.0
- How you installed PyTorch and PyG (conda, pip, source):
```
mamba install pytorch pytorch-lightning scikit-learn networkx scipy
pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.0%2Bcu116.html
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.12.0%2Bcu116.html
```

**Comment by rusty1s** [comment] 2022-07-07 09:20
Thanks! I can indeed reproduce. Only happens with PyTorch Lightning and indeed related to the changes of `DynamicInheritance` in the `Batch` class (cc @mananshah99).

**Comment by Amadeus-System** [comment] 2022-07-07 15:42
I'm glad that the problem will be resolved!!

**Comment by mananshah99** [comment] 2022-07-25 23:18
#5051 should close this issue. Thank you for reporting!

**Closed** 2022-07-26 18:31 UTC
Labels: bug

**Comment by de-gozaru** [comment] 2022-08-15 10:00
> #5051 should close this issue. Thank you for reporting!

Hi @mananshah99 
I just installed pytorch_geometric using `pip3 install pyg-nightly`, my current version is `2.1.0.dev20220815`, but I'm still facing the same problem with pytorch-lightining, can you tell me how to solve this problem?

**Comment by rusty1s** [comment] 2022-08-15 10:53
Can you ensure that you uninstalled the previous version of PyG? What does
```
import torch_geometric
print(torch_geometric.__version__)
```
report?

**Comment by de-gozaru** [comment] 2022-08-15 11:07
Hi @rusty1s 
It returns `2.1.0.dev20220815`, the same version I pasted before

**Comment by rusty1s** [comment] 2022-08-15 11:09
Can you try to run the above snippet from https://github.com/pyg-team/pytorch_geometric/issues/4848#issuecomment-1177233531. This works just fine for me.

**Comment by de-gozaru** [comment] 2022-08-15 11:33
Hi @rusty1s 
Thanks for the prompt reply, here is the output of the snippet:
```
Processing...
Done!
batch:
DataBatch(edge_index=[2, 14], num_nodes=9, x=[9, 5], batch=[9], ptr=[3])
batch.x:
tensor([[1.0000, 2.0000, 2.0000, 2.0000, 0.0000],
        [2.0000, 1.0000, 2.0000, 1.5000, 0.7071],
        [2.0000, 1.0000, 2.0000, 1.5000, 0.7071],
        [1.0000, 2.0000, 2.0000, 2.0000, 0.0000],
        [1.0000, 2.0000, 2.0000, 2.0000, 0.0000],
        [2.0000, 1.0000, 2.0000, 1.5000, 0.7071],
        [2.0000, 2.0000, 2.0000, 2.0000, 0.0000],
        [2.0000, 1.0000, 2.0000, 1.5000, 0.7071],
        [1.0000, 2.0000, 2.0000, 2.0000, 0.0000]])
```
also
```
import torch
import torch_geometric

print(torch.__version__)
print(torch_geometric.__version__)
```
returns
```
1.12.1+cu116
2.1.0.dev20220815
```

**Comment by rusty1s** [comment] 2022-08-15 11:44
Thanks! Do you have another script to reproduce the issue on your end?

**Comment by de-gozaru** [comment] 2022-08-15 11:54
Hi @rusty1s 

the code base I'm using is quite big, and it's hard for me to isolate the non functioning part, but the error I get now is:
```bash
File "train.py", line 151, in main
    trainer.fit(model, shape_matching_datamodule)
  File "/path/to/env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/path/to/env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/path/to/env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/path/to/env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1138, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/path/to/env/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1438, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "/path/to/env/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn
    fn(*args, **kwargs)
  File "path/to/MyCode/datasets/my_custom_datamodule.py", line 44, in setup
    self.train_datasets.append(dataset.get_dataset("train"))
  File "path/to/MyCode/datasets/in_memory_shape_dataset.py", line 82, in get_dataset
    self.do_subset_update()
  File "path/to/MyCode/datasets/my_custom_dataset_in_memory.py", line 114, in do_subset_update
    self.load_corres_files(self.chosen_ind)
  File "path/to/MyCode/datasets/my_custom_dataset_in_memory.py", line 130, in load_corres_files
    self.len_dict[i] = self.get(i).verts.size(0)
  File "/path/to/env/lib/python3.8/site-packages/torch_geometric/data/in_memory_dataset.py", line 84, in get
    data = separate(
  File "/path/to/env/lib/python3.8/site-packages/torch_geometric/data/separate.py", line 37, in separate
    data_store[attr] = _separate(attr, batch_store[attr], idx, slices,
  File "/path/to/env/lib/python3.8/site-packages/torch_geometric/data/separate.py", line 65, in _separate
    value = value.narrow(cat_dim or 0, start, end - start)
RuntimeError: start (0) + length (9994) exceeds dimension size (3).

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by rusty1s** [comment] 2022-08-15 15:15
So does that mean the error is no longer related to the error of this issue? Can you debug the input shape of `value` and the values of `cat_dim`, `start` and `end`?

**Comment by de-gozaru** [comment] 2022-08-15 15:28
Hi @rusty1s 
This error only appeared when I installed the nightly version, the code was working correctly before!
I'll try to debug as you suggested

**Comment by rusty1s** [comment] 2022-08-17 09:15
@de-gozaru This will be finally resolved with https://github.com/pyg-team/pytorch_geometric/pull/5210. Thanks for your patience!

**Comment by de-gozaru** [comment] 2022-08-19 14:00
Hi @rusty1s 
Thanks a lot for your answer!
what version of pyg should I install now?

**Comment by rusty1s** [comment] 2022-08-19 14:08
You need PyG 2.1.0 :)

**Comment by de-gozaru** [comment] 2022-08-19 14:11
Hi @rusty1s 
Thank you for your response!
should I install the version in master, or the version in pip is already updated, i.e
```
pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cu116.html
```

**Comment by rusty1s** [comment] 2022-08-19 14:16
You can use `pip`:
```
pip install --upgrade torch-geometric
```
is all you need to do.

**Comment by de-gozaru** [comment] 2022-08-19 14:48
Hi @rusty1s 
I'm still getting the same error I was getting before (see [here](https://github.com/pyg-team/pytorch_geometric/issues/4848#issuecomment-1214928692)). Please note that the code works correctly without the newer version

here are again my versions:
```
import torch
import torch_geometric

print(torch.__version__)
print(torch_geometric.__version__)
```
```
1.12.1+cu116
2.1.0
```

**Comment by de-gozaru** [comment] 2022-08-19 15:00
Hi @rusty1s 
If I downgrade to version 2.0.4, the code is working again, but I have the noisy warning again:
```bash
lib/python3.8/site-packages/torch_geometric/data/collate.py:150: UserWarning: An output with one or more elements was resized since it had shape [900], which does not match the required output shape [1, 30, 30]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:17.)
  value = torch.cat(values, dim=cat_dim or 0, out=out)
```

**Comment by rusty1s** [comment] 2022-08-20 07:27
Oh, what a bummer. I was pretty sure we fixed the root cause of this issue :( Is it possible for you to upload some dummy data of yours which we could use to try to reproduce? It would be also great if you could try to debug the execution of https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/data/separate.py#L59, e.g., what's the output of `print(key, value.shape, idx, cat_dim, start, end)` right before the crash?

If you wanna stay on 2.0.4, you can filter out the warning via `warnings.filterwarnings("ignore", ".*one or more elements.*")`

**Comment by de-gozaru** [comment] 2022-08-22 12:11
Hi @rusty1s 
Thanks for your response!
Indeed, I'm a little bit busy these days, and I'm already using the filtering solution. I hope I'll find some time to debug it soon.

**Comment by rusty1s** [comment] 2023-01-11 10:34
This should have been fixed a long time ago. If you can share a small example to reproduce the issue I am happy to look into it.
