### ISSUE TITLE
CaptumExplainer binary graph classification

### ISSUE THREAD

**Issue by Takaogahara** [pyg-team/pytorch_geometric#8214] opened 2023-10-17 18:16 UTC
### 🐛 Describe the bug

Hello,

A while ago, I commented in #7702 about the impossibility of using CaptumExplainer with binary classification, which was corrected in PR #7787. However, I only use the fixed implementation now due to the release update.

However, a function converts binary classification to multi-class classification in `torch_geometric.explain.algorithm.captum.py` postprocess function (line 88).

Here is a code to reproduce the error:

```python
import torch
from tqdm import tqdm
import os.path as osp
import torch.nn as nn
from torch_geometric.loader import DataLoader
from torch_geometric.datasets import MoleculeNet
from torch_geometric.nn import GAT, global_mean_pool
from torch_geometric.explain import Explainer, CaptumExplainer


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


dataset = "hiv"
path = osp.join(osp.dirname(osp.realpath(__file__)), "MoleculeNet")
dataset = MoleculeNet(path, dataset)
loader = DataLoader(dataset, batch_size=32, shuffle=True)

model = GAT(in_channels=dataset.num_node_features,
            hidden_channels=64,
            out_channels=1,
            num_layers=1,
            dropout=0.2,
            edge_dim=dataset.num_edge_features,
            v2=True,
            heads=2)

model = model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.BCEWithLogitsLoss()

model.train()
for epoch in tqdm(range(1, 2), ncols=120):
    for batch in loader:
        batch.to(device)
        optimizer.zero_grad()

        out = model(x=batch.x.float(), edge_index=batch.edge_index,
                    edge_attr=batch.edge_attr.float())
        out = global_mean_pool(out, batch.batch)
        pred = torch.sigmoid(out)

        loss = loss_fn(pred, batch.y)
        loss.backward()
        optimizer.step()


explainer = Explainer(model=model,
                      algorithm=CaptumExplainer("IntegratedGradients"),
                      explanation_type="model",
                      node_mask_type="attributes",
                      edge_mask_type="object",
                      model_config=dict(mode="binary_classification",
                                        task_level="graph",
                                        return_type="probs"))

data = dataset[0].to(device)
dummy = torch.zeros(data.x.shape[0], dtype=int, device=device)

explanation = explainer(x=data.x.float(), edge_index=data.edge_index,
                        edge_attr=data.edge_attr.float())

print(explanation.available_explanations)
```

This is the Traceback I received.

``` bash
Traceback (most recent call last):
  File "/home/takaogahara/takaogahara/experiments/explain/issue.py", line 60, in <module>
    explanation = explainer(x=data.x.float(), edge_index=data.edge_index,
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/torch_geometric/explain/explainer.py", line 204, in __call__
    explanation = self.algorithm(
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/torch_geometric/explain/algorithm/captum_explainer.py", line 167, in forward
    attributions = self.attribution_method_instance.attribute(
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/captum/log/__init__.py", line 42, in wrapper
    return func(*args, **kwargs)
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/captum/attr/_core/integrated_gradients.py", line 274, in attribute
    attributions = _batch_attribution(
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/captum/attr/_utils/batching.py", line 78, in _batch_attribution
    current_attr = attr_method._attribute(
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/captum/attr/_core/integrated_gradients.py", line 351, in _attribute
    grads = self.gradient_func(
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/captum/_utils/gradient.py", line 112, in compute_gradients
    outputs = _run_forward(forward_fn, inputs, target_ind, additional_forward_args)
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/captum/_utils/common.py", line 487, in _run_forward
    return _select_targets(output, target)
  File "/home/takaogahara/virtualenvs/graphchem/lib/python3.10/site-packages/captum/_utils/common.py", line 506, in _select_targets
    raise AssertionError(
AssertionError: Tensor target dimension torch.Size([1, 19]) is not valid. torch.Size([19, 2])
```

I believe the postprocess function in the `captum.py` file needs to be updated to keep the binary classification data, am I right?

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.0.1+cu118
* OS: Ubuntu 22.04
* Python version: 3.10
* CUDA/cuDNN version: cu118
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip

**Comment by rachitk** [comment] 2023-11-23 20:36
I believe I am having the same issue, though I'm not entirely certain what the expected output of the model should be for binary classification (or for any of the options, actually) to confirm that it's not an issue with my code as opposed to the model itself. My setup is nearly identical to the minimally reproducible example by @Takaogahara above.

**Comment by rusty1s** [comment] 2023-11-23 20:52
The issue with the code above is that the global pooling is performed outside of the loop, thus making configuration and model not align anymore. This fixes it for me:
```python
import os.path as osp

import torch
import torch.nn as nn

from torch_geometric.datasets import MoleculeNet
from torch_geometric.explain import CaptumExplainer, Explainer
from torch_geometric.loader import DataLoader
from torch_geometric.nn import GAT, global_mean_pool

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

dataset = "hiv"
path = osp.join(osp.dirname(osp.realpath(__file__)), "MoleculeNet")
dataset = MoleculeNet(path, dataset)
loader = DataLoader(dataset, batch_size=32, shuffle=True)


class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.model = GAT(
            in_channels=dataset.num_node_features,
            hidden_channels=64,
            out_channels=1,
            num_layers=1,
            dropout=0.2,
            edge_dim=dataset.num_edge_features,
            v2=True,
            heads=2,
        )

    def forward(self, x, edge_index, edge_attr, batch):
        x = self.model(x, edge_index, edge_attr=edge_attr)
        return global_mean_pool(x, batch)


model = Model().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.BCEWithLogitsLoss()

explainer = Explainer(
    model=model,
    algorithm=CaptumExplainer("IntegratedGradients"),
    explanation_type="model",
    node_mask_type="attributes",
    edge_mask_type="object",
    model_config=dict(mode="binary_classification", task_level="graph",
                      return_type="probs"),
)

data = dataset[0].to(device)

explanation = explainer(
    x=data.x.float(),
    edge_index=data.edge_index,
    edge_attr=data.edge_attr.float(),
    batch=torch.zeros(data.num_nodes, dtype=torch.long, device=device),
)

print(explanation.available_explanations)

**Comment by rusty1s** [comment] 2023-11-24 07:25
There is, however an issue, that `CaptumExplainer` does only seem to be able to support single predictions, so in node classification cases, you currently have to input `index=node_to_predict`.

**Comment by rusty1s** [comment] 2023-11-26 11:13
Fixed in https://github.com/pyg-team/pytorch_geometric/pull/8440.

**Closed** 2023-11-26 11:21 UTC
Labels: bug

**Comment by rachitk** [comment] 2023-11-30 17:24
Thanks! I think the bug when `index` was undefined was where I was having the issue as the user mentioned above, though I am facing a different bug now (`*** RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.`). 

I will make a new issue regarding that bug as I think it is unrelated (it seems to be specific to heterogeneous graphs).

**Comment by Moemenhussein11** [comment] 2024-07-07 12:49
hey @rachitk did you find a solution for the issue of  (*** RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.).

**Comment by rusty1s** [comment] 2024-07-08 10:11
What happens if you install `captum` via `pip install captum<0.7.0`?

**Comment by rusty1s** [comment] 2024-07-08 11:15
Can you share a small reproducible example in this case?

**Comment by Moemenhussein11** [comment] 2024-07-08 12:46
@rusty1s  please, see my question at::  https://github.com/pyg-team/pytorch_geometric/discussions/9495#discussion-6911687

**Comment by Takaogahara** [comment] 2024-07-19 13:52
@Moemenhussein11 and @rusty1s, is there a solution this issue `RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.`?

I was looking around and found that `CaptumExplainer` works setting `edge_mask_type=None`, as mentioned in #8496. However, I would like to use `edge_mask_type='object'`.

**Comment by Moemenhussein11** [comment] 2024-07-19 17:58
@Takaogahara, I found no alternative solution except for `edge_mask_type=None`. This implies that `CaptumExplainer` is unable to generate an abstract graph.

**Comment by rusty1s** [comment] 2024-08-19 12:46
It works fine on my end. Do you have a simple reproducible script?
