### ISSUE TITLE
*** NotImplementedError: Caught NotImplementedError in replica 0 on device 4.

### ISSUE THREAD

**Issue by onlyonewater** [pyg-team/pytorch_geometric#8391] opened 2023-11-16 19:12 UTC
### 🐛 Describe the bug

Hi, pyg team, I am a freshman about pyg package, now I am running the code in https://github.com/ketatam/DiffDock-PP, I git clone the repo, and prepare the environment, I use the command `bash ./src/train.sh`, I set the NUM_GPUS=4 with BATCH_SIZE=4 in data_parallel mode, but now it got an error like this:

```
*** NotImplementedError: Caught NotImplementedError in replica 0 on device 4.
Original Traceback (most recent call last):
  File "/mnt/workspace/duhao/.conda/envs/diffdock_pp/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/mnt/workspace/duhao/.conda/envs/diffdock_pp/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/workspace/duhao/.conda/envs/diffdock_pp/lib/python3.10/site-packages/torch_geometric/nn/data_parallel.py", line 69, in forward
    inputs = self.scatter(data_list, self.device_ids)
  File "/mnt/workspace/duhao/.conda/envs/diffdock_pp/lib/python3.10/site-packages/torch_geometric/nn/data_parallel.py", line 77, in scatter
    count = torch.tensor([data.num_nodes for data in data_list])
  File "/mnt/workspace/duhao/.conda/envs/diffdock_pp/lib/python3.10/site-packages/torch_geometric/data/feature_store.py", line 515, in __iter__
    raise NotImplementedError
NotImplementedError
```
I do not know why, it seems that the model can get an error when it forward. And I only use the Nvidia AMP package to decrease my GPU memory, I set the opt_level as O1, and `amp.initialize(model, optimizer, opt_level='O1')` before `DataParallel(model, device_ids=device_ids)`

### Environment

* PyG version: 2.4.0
* PyTorch version: 1.12.1
* OS: Ubuntu 20.04
* Python version: 3.10.8
* CUDA/cuDNN version: 11.3
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`): torch-scatter

**Comment by onlyonewater** [comment] 2023-11-16 19:40
or it seems that using DataParallel with amp may cause some bug?

**Comment by rusty1s** [comment] 2023-11-17 08:03
Duplicate of https://github.com/pyg-team/pytorch_geometric/discussions/8390.

**Closed by rusty1s** 2023-11-17 08:03 UTC
Labels: bug
