### ISSUE TITLE
Required parameter edge_index is empty

### ISSUE THREAD

**Issue by rfhari** [pyg-team/pytorch_geometric#1760] opened 2020-10-26 23:21 UTC
## 🐛 Bug

File "/home/cmu/anaconda3/envs/pytorch-geo/lib/python3.8/site-packages/torch_geometric/nn/conv/utils/inspector.py", line 58, in distribute
    raise TypeError(f'Required parameter {key} is empty.')

TypeError: Required parameter size is empty.

## To Reproduce

Check nn\conv\message_passing.py: Required parameter edge_index is empty

## Expected behavior

This error should not happen since it is internal to PyG. I'm using PyG 1.6.1, but contrary to the comments (mentioned in #1064 and #1369), this bug is still observed in the new version also.

## Environment

* OS: Ubuntu 18.04
* Python version: 3.8.5
* PyTorch version: 1.6.0
* CUDA/cuDNN version: 10.2

## Additional context

It is not clear how to apply the suggested 'fix' in #1064 to get back to old behavior. Where exactly should be modified?

**Comment by rusty1s** [comment] 2020-10-27 09:37
I cannot reproduce this. The following code runs fine for me:
```python
import torch
from torch_geometric.nn import MessagePassing


class MyConv(MessagePassing):
    def __init__(self):
        super(MyConv, self).__init__(aggr='mean')

    def forward(self, x, edge_index):
        return self.propagate(edge_index, x=x)

    def message(self, x_j, edge_index):
        print(edge_index.shape)
        return x_j


conv = MyConv()

edge_index = torch.randint(0, 10, (2, 20), dtype=torch.long)
x = torch.randn(10, 32)

conv(x, edge_index)
```

**Comment by nicoperetti** [comment] 2020-11-13 03:24
I got the same problem.

TypeError: Required parameter size is empty.

It happen when you have the size argument in message method. In my case I didn't need it at all so I have removed it from the method and It has worked. I share it just in case.

In order to reproduce the issue:

```python
import torch
from torch_geometric.nn import MessagePassing


class MyConv(MessagePassing):
    def __init__(self):
        super(MyConv, self).__init__(aggr='mean')

    def forward(self, x, edge_index):
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j, edge_index, size):
        return x_j


conv = MyConv()

edge_index = torch.randint(0, 10, (2, 20), dtype=torch.long)
x = torch.randn(10, 32)

conv(x, edge_index)
```

**Comment by rusty1s** [comment] 2020-11-13 13:40
Still cannot reproduce using PyG from master:
```
pip install git+https://github.com/rusty1s/pytorch_geometric.git
```
Can you check by using the latest PyG version? This seems to be already fixed in master.

**Comment by nicoperetti** [comment] 2020-11-13 14:57
It has already been fixed in the latest version of PyG. I have test it again the code above and It have worked correctly.

**Closed** 2022-10-26 23:31 UTC
