### ISSUE TITLE
GNNExplainer runtime error

### ISSUE THREAD

**Issue by cxw-droid** [pyg-team/pytorch_geometric#5391] opened 2022-09-08 17:18 UTC
### 🐛 Describe the bug

When I run example/gnn_explainer.py, there is an error as follows,

`RuntimeError: The size of tensor a (13264) must match the size of tensor b (19) at non-singleton dimension 0`

It threw error finally here:
https://github.com/pyg-team/pytorch_geometric/blob/40ad1afc96a9cf1b39571549f37de983ca6100d8/examples/gnn_explainer.py#L25

The error was traced back to:
 https://github.com/pyg-team/pytorch_geometric/blob/40ad1afc96a9cf1b39571549f37de983ca6100d8/examples/gnn_explainer.py#L47

I debugged and found here the length of `edge_index` and the length `edge_weight` do not match. The length of `edge_index` was reduced to 19 while the `edge_weight` was still 13264 inside the `explain_node()`

### Environment

* PyG version: 2.0.4
* PyTorch version: 1.10.1
* OS: Ubuntu 18.04
* Python version: 3.9.12
* CUDA/cuDNN version: 10.2
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by EdisonLeeeee** [comment] 2022-09-09 01:54
Hi @cxw-droid 

This issue was resolved in PyG 2.1.0. Have a try on `pip install -U torch_geometric` and it should work fine.

**Closed** 2022-09-09 07:41 UTC
Labels: bug

**Comment by cxw-droid** [comment] 2022-09-09 15:27
Thank, it is fixed. But there is still another problem. When I run [this code](https://github.com/pyg-team/pytorch_geometric/blob/0da9e1903c3b8ffd41b9a51b9e481dd1ba616a7f/examples/gnn_explainer_ba_shapes.py), there is an error like this,

>Traceback (most recent call last):
  File "pytorch_geometric/examples/gnn_explainer_ba_shapes.py", line 51, in <module>
    loss = train()
  File "pytorch_geometric/examples/gnn_explainer_ba_shapes.py", line 28, in train
    out = model(data.x, data.edge_index, data.edge_weight)
  File "miniconda3/envs/torch1.10/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given

**Comment by EdisonLeeeee** [comment] 2022-09-09 15:53
I can indeed reproduce this and it looks like it could be a bug. To resolve this, please specify `edge_weight` as a keyword argument during model forward. E.g., in line 28:
```python
out = model(data.x, data.edge_index, edge_weight=data.edge_weight)
```

Also, in line 39:
```python
pred = model(data.x, data.edge_index, edge_weight=data.edge_weight).argmax(dim=-1)

```
