### ISSUE TITLE
Assert in RandomLinkSplit

### ISSUE THREAD

**Issue by fierval** [pyg-team/pytorch_geometric#6823] opened 2023-03-01 04:03 UTC
### 🐛 Describe the bug

```python
train, val, test = \
          RandomLinkSplit(num_val=0.1, num_test=0.1, neg_sampling_ratio=1, add_negative_train_samples=True) \
         (dataset)
```

Asserts in `self._create_label` called from line 231 in `random_link_split.py` , the actual assert is inside the function on line 304:
```python
assert edge_label.size(0) == store.edge_index.size(1)
```
The data looks like:
```python
Data(x=[3306,512], edge_index=[2, 12200],  edge_label=[12200])
```
The complaint is that the `edge_label` size of the split ("train") in this case is not equal to the size of edges in the store. If I set `add_negative_train_samples=False`, the first call to `_create_label` succeeds, because this check is bypassed, but the second one, involving validation edges, fails. 

The failure seems reasonable, since the number of edges in the store == 12200, i.e. edges of the entire graph, but the split already has fewer edges: 1220 in the case of validation split + there should be 1220 new negative edges. 

So this assert seems like a bug to me, but maybe I'm missing something?

### Environment

* PyG version: 2.2.0
* PyTorch version:
* OS: Win11
* Python version: 3.9
* CUDA/cuDNN version: 11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source): pip
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment] 2023-03-01 14:22
Try `neg_sampling_ratio=0.0`

**Comment by fierval** [comment] 2023-03-01 14:26
I know that works because it bypasses the problematic assert. But what if I want to generate negative edges during the split?

**Comment by rusty1s** [comment] 2023-03-01 17:20
Mh, I cannot really reproduce this. I added an additional test for this here: https://github.com/pyg-team/pytorch_geometric/pull/6831/files

**Comment by rusty1s** [comment] 2023-03-01 17:21
Oh, it looks like this is already fixed on master.
```
pip install git+https://github.com/pyg-team/pytorch_geometric.git
```
should fix this. Sorry for any inconveniences.

**Closed by rusty1s** 2023-03-01 17:21 UTC
Labels: bug

**Comment by fierval** [comment] 2023-03-01 18:02
Verified. Thanks! 😄
