### ISSUE TITLE
Error with model.load_state_dict using PyG 2.4.0 while PyG 2.3.1 loads successfully

### ISSUE THREAD

**Issue by dttsou** [pyg-team/pytorch_geometric#8420] opened 2023-11-22 04:01 UTC
### 🐛 Describe the bug

Scenario:

I trained a model using PyG 2.4.0, and saved it to a file using torch.save( model.state_dict(), filename ).

Then later on, I try to reload that model back from file by using:
mod_state_dict = torch.load( filename, map_location=torch.device("cpu") )
model.load_state_dict( mod_state_dict)

I have been using the same code for a few months now without errors (using PyG 2.3.1), and this is the first time I am doing this process with PyG 2.4.0 and getting errors.

When I try using PyG 2.4.0, I get a whole bunch of the following types of errors:
While copying the parameter named "node_encoder.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([50, 7]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (7) at non-singleton dimension 1',).
While copying the parameter named "edge_encoder.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([50, 1]), an exception occurred : ("output with shape [0] doesn't match the broadcast shape [50, 0]",).

However, if downgrade back to PyG 2.3.1 (conda install pyg==2.3.1 -c pyg), and rerun the same code, it works successfully. Note that I can save the model trained using PyG 2.4.0 and reloaded it successfully in PyG 2.3.1, however, cannot reload it in PyG 2.4.0.

Has something changed about PyG 2.4.0 which requires me to do something different, or is this a bug?

### Environment

* PyG version: 2.4.0
* PyTorch version: 2.0.1
* OS: Windows 11
* Python version: 3.9.18
* CUDA/cuDNN version: 11.7
* How you installed PyTorch and PyG (`conda`, `pip`, source): conda
* Any other relevant information (*e.g.*, version of `torch-scatter`):

**Comment by rusty1s** [comment] 2023-11-23 17:02
This looks like a bug. Do you have a small example to reproduce this? Does this happen on any model?

**Comment by AdrianSchneble** [comment] 2023-11-28 15:39
Seems to be the same problem discussed here: https://github.com/pyg-team/pytorch_geometric/discussions/8422

**Comment by dttsou** [comment] 2023-12-11 06:39
Sorry its taken me a while to create a reproduction scenario.

I've cut everything down to as barebones as possible to reproduce a similar behavior, and this is what I've come up with.

# Create reproduction model
import torch
from torch_geometric.data import HeteroData, Data, Batch
from torch_geometric.loader import DataLoader
from torch_geometric.nn import Linear, GATv2Conv, GENConv, GeneralConv, TransformerConv, to_hetero, BatchNorm, LayerNorm, MaxAggregation, SumAggregation, MinAggregation, MeanAggregation, SoftmaxAggregation
from os.path import exists
import torch.nn.functional as F
import torch.nn as nn
from torch.nn import Sigmoid, ReLU, PReLU
import numpy as np
import math
import os
from datetime import datetime

class TestNN(torch.nn.Module):
    def __init__(self, hidden_channels, out_channels):
        super().__init__()
        self.node_encoder = Linear(-1, hidden_channels)
        self.edge_encoder = Linear(-1, hidden_channels)
        self.layer1Conv = GATv2Conv(hidden_channels, out_channels, edge_dim=hidden_channels)

    def forward(self, hdata):
        x = hdata['candidate'].x
        edge_index_tc = hdata['candidate', 'likes', 'candidate'].edge_index
        edge_attr_tc = hdata['candidate', 'likes', 'candidate'].edge_attr
        x = self.node_encoder(x)
        edge_attr_tc = self.edge_encoder(edge_attr_tc)
        x = self.layer1Conv(x, edge_index_tc, edge_attr_tc)
        return x

# Create reproduction data
dlist = []
x = torch.tensor([[2,1],[5,6],[3,7],[12,0]], dtype=torch.float)
y = torch.tensor([0,1,0,1], dtype=torch.float)
edge_index = torch.tensor([[0, 1, 2, 0, 3], [1, 0, 1, 3, 2]], dtype=torch.long)
edge_index2 = torch.tensor([[0, 2, 1], [2, 0, 2]], dtype=torch.long)
edge_attr = torch.tensor([[0.5,0.1],[0.3,0.3],[0.2,0.25],[0.5,0.7],[0.9,0.7]], dtype=torch.float)
data = HeteroData()
data['candidate'].x = x
data['candidate'].y = y
data['candidate', 'likes', 'candidate'].edge_index = edge_index
data['candidate', 'likes', 'candidate'].edge_attr = edge_attr
data.ids = 66
dlist.append(data)

x = torch.tensor([[0,1],[1,2],[2,3],[3,4]], dtype=torch.float)
y = torch.tensor([0,1,0,1], dtype=torch.float)
edge_index = torch.tensor([[0, 1, 2, 0, 3], [1, 0, 1, 3, 2]], dtype=torch.long)
edge_index2 = torch.tensor([[0, 2, 1], [2, 0, 2]], dtype=torch.long)
edge_attr = torch.tensor([[0.5,0.1],[0.3,0.3],[0.2,0.25],[0.5,0.7],[0.9,0.7]], dtype=torch.float)
data = HeteroData()
data['candidate'].x = x
data['candidate'].y = y
data['candidate', 'likes', 'candidate'].edge_index = edge_index
data['candidate', 'likes', 'candidate'].edge_attr = edge_attr
data.ids = 77
dlist.append(data)

x = torch.tensor([[3,3],[3,3],[3,3],[3,4]], dtype=torch.float)
y = torch.tensor([0,1,0,1], dtype=torch.float)
edge_index = torch.tensor([[0, 1, 2, 0, 3], [1, 0, 1, 3, 2]], dtype=torch.long)
edge_index2 = torch.tensor([[0, 2, 1], [2, 0, 2]], dtype=torch.long)
edge_attr = torch.tensor([[0.5,0.1],[0.3,0.3],[0.2,0.25],[0.5,0.7],[0.9,0.7]], dtype=torch.float)
data = HeteroData()
data['candidate'].x = x
data['candidate'].y = y
data['candidate', 'likes', 'candidate'].edge_index = edge_index
data['candidate', 'likes', 'candidate'].edge_attr = edge_attr
data.ids = 88
dlist.append(data)

loader = DataLoader(dlist, batch_size=3, shuffle=True)
batch = next(iter(loader))

gnn = TestNN(15,1)
x = gnn(batch)

# Save model and load into another newly initiated model
filename = 'D:/tmp/test_gnn.pt'
torch.save( gnn.state_dict(), filename )

gnn2 = TestNN(15,1)
state_dict_loaded = torch.load(filename)
gnn2.load_state_dict(state_dict_loaded)

#######################
This is the resulting output, which is basically the same as my original error message.
RuntimeError: Error(s) in loading state_dict for TestNN:
	While copying the parameter named "node_encoder.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([15, 2]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (2) at non-singleton dimension 1',).
	While copying the parameter named "edge_encoder.weight", whose dimensions in the model are torch.Size([0]) and whose dimensions in the checkpoint are torch.Size([15, 2]), an exception occurred : ('The size of tensor a (0) must match the size of tensor b (2) at non-singleton dimension 1',).

**Comment by rusty1s** [comment] 2023-12-12 09:43
Yeah, this is already fixed on master. Sorry for the inconvenience :(

**Closed by rusty1s** 2023-12-12 09:43 UTC
Labels: bug

**Comment by dttsou** [comment] 2023-12-13 02:43
Thank you, no apologies needed, really appreciate you making this package!
