### ISSUE TITLE
Function to print model summary like in keras

### ISSUE THREAD

**Issue by varun-vasudevan** [pyg-team/pytorch_geometric#641] opened 2019-08-22 20:26 UTC
## 🚀 Feature 

Function to print a summary representation of the model like in `keras`.

## Motivation

It is useful to see a summary of the model for clarity and debugging purposes. 

## Example

If I were to print a summary for the model in `mnist_graclus.py` under the examples directory in `pytorch_geometric` library then it would look something like:

----------------------------------------------------------------
     Layer.Parameter         Param Tensor Shape         Param #
----------------------------------------------------------------
        conv1.weight                [25, 1, 32]             800
          conv1.root                    [1, 32]              32
          conv1.bias                       [32]              32
        conv2.weight               [25, 32, 64]           51200
          conv2.root                   [32, 64]            2048
          conv2.bias                       [64]              64
          fc1.weight                  [128, 64]            8192
            fc1.bias                      [128]             128
          fc2.weight                  [10, 128]            1280
            fc2.bias                       [10]              10
----------------------------------------------------------------
Total params: 63786
Trainable params: 63786
Non-trainable params: 0

The following code prints the above summary.
```
def gnn_model_summary(model):
    
    model_params_list = list(model.named_parameters())
    print("----------------------------------------------------------------")
    line_new = "{:>20}  {:>25} {:>15}".format("Layer.Parameter", "Param Tensor Shape", "Param #")
    print(line_new)
    print("----------------------------------------------------------------")
    for elem in model_params_list:
        p_name = elem[0] 
        p_shape = list(elem[1].size())
        p_count = torch.tensor(elem[1].size()).prod().item()
        line_new = "{:>20}  {:>25} {:>15}".format(p_name, str(p_shape), str(p_count))
        print(line_new)
    print("----------------------------------------------------------------")
    total_params = sum([param.nelement() for param in model.parameters()])
    print("Total params:", total_params)
    num_trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print("Trainable params:", num_trainable_params)
    print("Non-trainable params:", total_params - num_trainable_params)
```

**Comment by rusty1s** [comment] 2019-08-22 20:56
Thank you for providing the code to print the summary model. I guess this is more of a PyTorch issue than a PyTorch Geometric issue, isn‘t it?

**Comment by varun-vasudevan** [comment] 2019-08-22 21:16
I wouldn't disagree with you. I wasn't sure how to accomplish the task using the [summary](https://github.com/sksq96/pytorch-summary/blob/master/torchsummary/torchsummary.py) function described in this [post](https://discuss.pytorch.org/t/is-there-similar-pytorch-function-as-model-summary-as-keras/2678/4) because I didn't know what to give as input size. That's why I bothered writing a function myself. I could be completely wrong.

**Comment by wjlpku** [comment] 2020-06-04 04:25
Hi, I also wonder how to count the number of parameters and flops in the network.

**Comment by rusty1s** [comment] 2022-10-27 06:18
Duplicate of https://github.com/pyg-team/pytorch_geometric/issues/5727.

**Closed by rusty1s** 2022-10-27 06:18 UTC
Labels: feature
